version: "3.5"

services:
  backend:
    container_name: backend
    image: backend
    ports:
      - 8082:8082
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:postgresql://data_base:5432/customers?User=root&password=admin",
            "keycloak.auth-server-url": "${KC_SERVICE_ADDR:-http://keycloak:8080/auth}"
          }'
    depends_on:
      - data_base
      - keycloak
    networks:
      - montana

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak_db
      DB_USER: root
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    depends_on:
      - keycloak_db
    links:
      - "keycloak_db:keycloak_db"
    networks:
      montana:
        aliases:
          - keylocal.vetermanve.com

  data_base:
    container_name: data_base
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - montana
    volumes:
      #- .docker/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - service_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin

  keycloak_db:
    container_name: keycloak_db
    image: postgres:13.1-alpine
    ports:
      - "5431:5431"
    restart: unless-stopped
    networks:
      - montana
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin

volumes:
  service_db:
  keycloak_db:

networks:
  montana:
    external: true
    name: montana_network
