CREATE TABLE codes
(
    uuid                 UUID        NOT NULL,
    code                 VARCHAR(20) NOT NULL,
    type_of_vocabulary   VARCHAR(10) NOT NULL,
    coder_organization   VARCHAR(3)  NOT NULL,
    version              VARCHAR(35) NOT NULL,
    CONSTRAINT pk_codes PRIMARY KEY (uuid)
);

CREATE TABLE companies
(
    uuid UUID NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_companies PRIMARY KEY (uuid)
);

CREATE TABLE employees
(
    uuid    UUID NOT NULL,
    user_id UUID,
    CONSTRAINT pk_employees PRIMARY KEY (uuid)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_in_companies
(
    uuid             UUID NOT NULL,
    company_uuid     UUID,
    role_id          BIGINT,
    role_issuer_uuid UUID,
    employee_uuid    UUID,
    CONSTRAINT pk_roles_in_companies PRIMARY KEY (uuid)
);

CREATE TABLE users
(
    uuid       UUID NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    patronymic VARCHAR(255),
    email      VARCHAR(255),
    phone      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (uuid)
);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_USERID_UUID FOREIGN KEY (user_id_uuid) REFERENCES users (uuid);

ALTER TABLE roles_in_companies
    ADD CONSTRAINT FK_ROLES_IN_COMPANIES_ON_COMPANY_UUID FOREIGN KEY (company_uuid) REFERENCES companies (uuid);

ALTER TABLE roles_in_companies
    ADD CONSTRAINT FK_ROLES_IN_COMPANIES_ON_EMPLOYEE_UUID FOREIGN KEY (employee_uuid) REFERENCES employees (uuid);

ALTER TABLE roles_in_companies
    ADD CONSTRAINT FK_ROLES_IN_COMPANIES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE roles_in_companies
    ADD CONSTRAINT FK_ROLES_IN_COMPANIES_ON_ROLEISSUER_UUID FOREIGN KEY (role_issuer_uuid) REFERENCES employees (uuid);